name: build

on: 
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package --file pom.xml
    
    - name: Run integration test with -Parq-payara-managed
      run: mvn -B -q clean verify -Parq-payara-managed,jersey   

    # - name: Run integration test with -Parq-payara-embedded
    #   run: mvn clean verify -Parq-payara-embedded,jersey -X

