name: Java CI

on: 
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package --file pom.xml
    
    - name: Run integration test with -Parq-payara-managed
      run: mvn clean verify -Parq-payara-managed,jersey        

    - name: Run integration test with -Parq-payara-embedded(chromeheadless)
      run: mvn clean verify -Parq-payara-embedded,jersey,chromeheadless

    - name: Run integration test with -Parq-payara-embedded
      run: mvn clean verify -Parq-payara-embedded,jersey
      
